<?php
    /** @var \Magento\Catalog\Block\Product\ProductList\Upsell $block */
    /** @var \Magento\Framework\View\TemplateEngine\Php $this */
    /** @var \Magento\Framework\Escaper $escaper */

    /** @var \Magento\Framework\Pricing\Helper\Data */
    $priceHelper = $this->helper('Magento\Framework\Pricing\Helper\Data');

    /** @var \Magento\Catalog\Helper\Image */
    $imageHelper = $this->helper('Magento\Catalog\Helper\Image');

    /** @var \Magento\Catalog\Model\Product[] */
    $_upsellProductList = $block->getItems();
?>

<?php if (empty($_upsellProductList)) return ?>

<div class="upsell">
    <div class="upsell-header">
        <h3 class="upsell-title">
            <?= __('We found other products you might like!') ?>
        </h3>
    </div>
    <div class="upsell-body">
        <ul class="upsell-list">
            <?php $upsellProductListKeys = array_keys($_upsellProductList) ?>
            <?php for ($i = 0; $i < count($upsellProductListKeys) && $i < 3; $i++): ?>
                <?php $upsellProduct = $_upsellProductList[$upsellProductListKeys[$i]] ?>
                <li class="upsell-item">
                    <div class="upsell-item-imagewr">
                        <img
                            class="upsell-item-image"
                            src="<?= $escaper->escapeHtmlAttr(
                                $imageHelper->init($upsellProduct, 'product_base_image')->getUrl()
                            ) ?>"
                            alt="<?= __('Product image') ?>"
                        />
                    </div>
                    <div class="upsell-item-content">
                        <h3 class="upsell-item-title">
                            <?= $escaper->escapeHtml(__($upsellProduct->getName())) ?>
                        </h3>
                        <div class="upsell-item-reviews">
                            <?= $block->getReviewsSummaryHtml($upsellProduct) ?>
                        </div>
                        <div class="upsell-item-price">
                            <?= $escaper->escapeHtml(__(
                                $priceHelper->currency($upsellProduct->getFinalPrice(), true, false)
                            )) ?>
                        </div>
                    </div>
                    <div class="upsell-item-view">
                        <a class="upsell-item-viewlink" href="
                            <?= $escaper->escapeHtmlAttr($upsellProduct->getProductUrl()) ?>
                        ">
                            <?= __('View product') ?>
                        </a>
                    </div>
                </li>
            <?php endfor ?>
        </ul>
    </div>
</div>
