<?php
    /** @var \Magento\Catalog\Block\Product\ProductList\Related $block */
    /** @var \Magento\Framework\View\TemplateEngine\Php $this */
    /** @var \Magento\Framework\Escaper $escaper */

    /** @var \Magento\Framework\Pricing\Helper\Data */
    $priceHelper = $this->helper('Magento\Framework\Pricing\Helper\Data');

    /** @var \Magento\Catalog\Helper\Image */
    $imageHelper = $this->helper('Magento\Catalog\Helper\Image');

    /** @var \Magento\Catalog\Model\Product[] */
    $_relatedProducts = $block->getItems()->getItems();
?>

<?php if (empty($_relatedProducts)) return ?>

<div class="related">
    <ul class="related-list">
        <?php $relatedProductKeys = array_keys($_relatedProducts) ?>
        <?php for ($i = 0; $i < count($relatedProductKeys) && $i < 6; $i++): ?>
            <?php $relatedProduct = $_relatedProducts[$relatedProductKeys[$i]] ?>
            <li class="related-item">
                <div class="relateditem">
                    <div class="relateditem-image-wr">
                        <img
                            class="relateditem-image"
                            src="<?= $escaper->escapeHtmlAttr(
                                $imageHelper->init($relatedProduct, 'product_base_image')->getUrl()
                            ) ?>"
                            alt="<?= __('Product image') ?>"
                        >
                    </div>
                    <div class="relateditem-title-wr">
                        <h3 class="relateditem-title">
                            <a class="relateditem-title-link" href="
                                <?= $escaper->escapeHtmlAttr($relatedProduct->getProductUrl()) ?>
                            "><?= $escaper->escapeHtml(__($relatedProduct->getName())) ?></a>
                        </h3>
                    </div>
                    <div class="relateditem-reviews-wr">
                        <?= $block->getReviewsSummaryHtml($relatedProduct) ?>
                    </div>
                    <div class="relateditem-price-wr">
                        <span class="relateditem-price">
                            <?= $escaper->escapeHtml(__(
                                $priceHelper->currency($relatedProduct->getFinalPrice(), true, false)
                            )) ?>
                        </span>
                    </div>
                    <div class="relateditem-addtocart-wr">
                        <button class="relateditem-addtocart-button">
                            <?= __('Add to Cart') ?>
                        </button>
                    </div>
                </div>
            </li>
        <?php endfor ?>
    </ul>
</div>
